.\" $Id: dspam_admin.1,v 1.2 2011/06/28 00:13:48 sbajic Exp $
.\"  -*- nroff -*-
.\"
.\" dspam_admin3.9
.\"
.\" Authors:	Stevan Bajic <stevan@bajic.ch>
.\"
.\" Copyright (C) 2002-2012 DSPAM Project
.\" All rights reserved
.\"
.TH dspam_admin 1  "Jan 03, 2010" "DSPAM" "DSPAM"

.SH NAME
dspam_admin \- Alter DSPAM users preferences

.SH SYNOPSIS
.na
.B dspam_admin
[\c
.B \--profile\c
=PROFILE\c
]
[\c
.I function\fR\c
]
[\c
.I argument\fR\c
]

.ad
.SH DESCRIPTION 
.LP
.B dspam_admin
is used to alter DSPAM user's preferences.

.SH OPTIONS
.LP

.ne 3
.TP
Add a Preference:\c
.B add\ preference\ \c
[\c
.I user\c
] [\c
.I attrib\c
] [\c
.I value\c
]\c

.ne 3
.TP
Set/change a Preference:\c
.B change\ preference\ \c
[\c
.I user\c
] [\c
.I attrib\c
] [\c
.I value\c
]\c

.ne 3
.TP
Delete a Preference:\c
.B delete\ preference\ \c
[\c
.I user\c
] [\c
.I attrib\c
] [\c
.I value\c
]\c

.ne 3
.TP
List Preferences:\c
.B list\ preference\ \c
[\c
.I user\c
] [\c
.I attrib\c
] [\c
.I value\c
]\c

.ne 3
.TP
Aggregate Preferences:\c
.B aggregate\ preference\ \c
[\c
.I user\c
]\c

.LP
Use\ \c
.B default\ \c
as username to modify the default (uid 0) user preference.


.SH EXIT VALUE
.LP
.ne 3
.PD 0
.TP
.B 0
Operation was successful.
.ne 3
.TP
.B other
Operation resulted in an error. 
.PD

.SH COPYRIGHT
Copyright \(co 2002\-2012 DSPAM Project
.br
All rights reserved.
.br

For more information, see http://dspam.sourceforge.net.

.SH SEE ALSO
.BR dspam (1),
.BR dspam_clean (1),
.BR dspam_crc (1),
.BR dspam_dump (1),
.BR dspam_logrotate (1),
.BR dspam_merge (1),
.BR dspam_stats (1),
.BR dspam_train (1)
